config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      this_repo:
        commands:
        - git rev-parse --is-inside-work-tree
        container: qc.acc_chewy-rose-hyena
  QC.Doc:
    repos:
      this_repo:
        commands:
        - find_doc_files.py --file-type *.rst --path .
        container: qc.doc_lumpy-xanthic-stoat
  QC.Lic:
    repos:
      this_repo:
        commands:
        - licensee detect . --json
        container: qc.lic_geeky-magenta-millipede
  QC.Sty:
    repos:
      this_repo:
        commands:
        - pycodestyle .
        container: qc.sty_bluesy-amaranth-dodo
timeout: 600
